FROM python:3.8.10
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /wemake-src
COPY ./django/src/requirements.txt /wemake-src/
RUN pip install -r requirements.txt
# COPY ./django/* /wemake-src/
